services:
  filebrowser:
    container_name: filebrowser
    # Tells Docker to build the image using the Dockerfile in your local root directory
    build: .
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "8000:80"
    volumes:
      - filebrowser_data:/srv
      - filebrowser_database:/database
      - filebrowser_config:/config
    environment:
      - FB_TOKEN_EXPIRATION_TIME : "87600h"
      - FB_REDIS_CACHE_URL: redis://default:filebrowser@redis:6379
    networks:
      - filebrowser

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    command:
      - sh
      - -c
      - |
        cat > /tmp/users.acl <<'EOF'
        user default on >filebrowser ~* +@all
        EOF
        exec redis-server --aclfile /tmp/users.acl
    networks:
      - filebrowser

networks:
  filebrowser:

volumes:
  filebrowser_data:
  filebrowser_database:
  filebrowser_config: